#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MonoWithWeChartSDK.Resource", IsApplication=true)]

namespace MonoWithWeChartSDK
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050005
			public const int send_appdata_item = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int send_emoji_item = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int send_emoji_item_format = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int send_file_item = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int send_img_item = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int send_music_item = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int send_video_item = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int send_webpage_item = 2131034116;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_loading_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_loading_white_01 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_loading_white_02 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_loading_white_03 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_loading_white_04 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_loading_white_05 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_loading_white_06 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_loading_white_07 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_loading_white_08 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_loading_white_09 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_loading_white_10 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_loading_white_11 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_loading_white_12 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int progress_drawable_white = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int MyButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int id_tv_loadingmsg = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int payresult = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SimpleDialog = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_back = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int app_cancel = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int app_continue = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int app_delete = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int app_edit = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int app_find = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int app_finish = 2130968589;
			
			// aapt resource value: 0x7f040024
			public const int app_name = 2130968612;
			
			// aapt resource value: 0x7f04000b
			public const int app_nextstep = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int app_ok = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int app_prevstep = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int app_save = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int app_send = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int app_set = 2130968584;
			
			// aapt resource value: 0x7f040025
			public const int app_share = 2130968613;
			
			// aapt resource value: 0x7f040006
			public const int app_tip = 2130968582;
			
			// aapt resource value: 0x7f040013
			public const int applet_seccode_fail_tip = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int applet_seccode_tip = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int applet_secimg_change = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int applet_secimg_title = 2130968592;
			
			// aapt resource value: 0x7f040054
			public const int check_pay = 2130968660;
			
			// aapt resource value: 0x7f04002c
			public const int check_timeline_supported = 2130968620;
			
			// aapt resource value: 0x7f040026
			public const int enter = 2130968614;
			
			// aapt resource value: 0x7f040032
			public const int errcode_cancel = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int errcode_deny = 2130968627;
			
			// aapt resource value: 0x7f040031
			public const int errcode_success = 2130968625;
			
			// aapt resource value: 0x7f040034
			public const int errcode_unknown = 2130968628;
			
			// aapt resource value: 0x7f04001f
			public const int fmt_afternoon = 2130968607;
			
			// aapt resource value: 0x7f040015
			public const int fmt_date = 2130968597;
			
			// aapt resource value: 0x7f040017
			public const int fmt_datetime = 2130968599;
			
			// aapt resource value: 0x7f04001c
			public const int fmt_dawn = 2130968604;
			
			// aapt resource value: 0x7f040020
			public const int fmt_evening = 2130968608;
			
			// aapt resource value: 0x7f040022
			public const int fmt_iap_err = 2130968610;
			
			// aapt resource value: 0x7f04001a
			public const int fmt_in60min = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int fmt_justnow = 2130968603;
			
			// aapt resource value: 0x7f040016
			public const int fmt_longdate = 2130968598;
			
			// aapt resource value: 0x7f040019
			public const int fmt_longtime = 2130968601;
			
			// aapt resource value: 0x7f04001d
			public const int fmt_morning = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int fmt_noon = 2130968606;
			
			// aapt resource value: 0x7f040018
			public const int fmt_patime = 2130968600;
			
			// aapt resource value: 0x7f040021
			public const int fmt_pre_yesterday = 2130968609;
			
			// aapt resource value: 0x7f04005a
			public const int get_access_token_fail = 2130968666;
			
			// aapt resource value: 0x7f040059
			public const int get_access_token_succ = 2130968665;
			
			// aapt resource value: 0x7f04002e
			public const int get_from_wx_title = 2130968622;
			
			// aapt resource value: 0x7f04005e
			public const int get_prepayid_fail = 2130968670;
			
			// aapt resource value: 0x7f04005d
			public const int get_prepayid_succ = 2130968669;
			
			// aapt resource value: 0x7f04004f
			public const int get_token_from_weixin = 2130968655;
			
			// aapt resource value: 0x7f040058
			public const int getting_access_token = 2130968664;
			
			// aapt resource value: 0x7f04005b
			public const int getting_prepayid = 2130968667;
			
			// aapt resource value: 0x7f04002a
			public const int goto_fav = 2130968618;
			
			// aapt resource value: 0x7f040029
			public const int goto_pay = 2130968617;
			
			// aapt resource value: 0x7f040028
			public const int goto_send = 2130968616;
			
			// aapt resource value: 0x7f040023
			public const int hello = 2130968611;
			
			// aapt resource value: 0x7f040036
			public const int input_openid = 2130968630;
			
			// aapt resource value: 0x7f040056
			public const int input_package_value = 2130968662;
			
			// aapt resource value: 0x7f040055
			public const int input_reqkey = 2130968661;
			
			// aapt resource value: 0x7f040037
			public const int input_scope = 2130968631;
			
			// aapt resource value: 0x7f040057
			public const int input_sign = 2130968663;
			
			// aapt resource value: 0x7f04003a
			public const int is_timeline = 2130968634;
			
			// aapt resource value: 0x7f040035
			public const int launch_from_wx = 2130968629;
			
			// aapt resource value: 0x7f04002b
			public const int launch_wx = 2130968619;
			
			// aapt resource value: 0x7f040052
			public const int pay_by_wx = 2130968658;
			
			// aapt resource value: 0x7f040030
			public const int pay_by_wx_title = 2130968624;
			
			// aapt resource value: 0x7f040053
			public const int pay_by_wxap = 2130968659;
			
			// aapt resource value: 0x7f040060
			public const int pay_result_callback_msg = 2130968672;
			
			// aapt resource value: 0x7f04005f
			public const int pay_result_tip = 2130968671;
			
			// aapt resource value: 0x7f04005c
			public const int paying = 2130968668;
			
			// aapt resource value: 0x7f040039
			public const int receive = 2130968633;
			
			// aapt resource value: 0x7f040027
			public const int reg = 2130968615;
			
			// aapt resource value: 0x7f04004e
			public const int register_as_weixin_app_sender = 2130968654;
			
			// aapt resource value: 0x7f040038
			public const int send = 2130968632;
			
			// aapt resource value: 0x7f040045
			public const int send_appdata = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int send_emoji = 2130968646;
			
			// aapt resource value: 0x7f04003f
			public const int send_file = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int send_file_file_not_exist = 2130968640;
			
			// aapt resource value: 0x7f04003d
			public const int send_img = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int send_img_file_not_exist = 2130968638;
			
			// aapt resource value: 0x7f040042
			public const int send_music = 2130968642;
			
			// aapt resource value: 0x7f040041
			public const int send_pic = 2130968641;
			
			// aapt resource value: 0x7f04003b
			public const int send_text = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int send_text_default = 2130968636;
			
			// aapt resource value: 0x7f04002d
			public const int send_to_wx_title = 2130968621;
			
			// aapt resource value: 0x7f040043
			public const int send_video = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int send_webpage = 2130968644;
			
			// aapt resource value: 0x7f04004d
			public const int share_appdata_to_weixin = 2130968653;
			
			// aapt resource value: 0x7f04004b
			public const int share_music_to_weixin = 2130968651;
			
			// aapt resource value: 0x7f04004a
			public const int share_pic_to_weixin = 2130968650;
			
			// aapt resource value: 0x7f040048
			public const int share_text_default = 2130968648;
			
			// aapt resource value: 0x7f040047
			public const int share_text_to_weixin = 2130968647;
			
			// aapt resource value: 0x7f040049
			public const int share_url_to_weixin = 2130968649;
			
			// aapt resource value: 0x7f04004c
			public const int share_video_to_weixin = 2130968652;
			
			// aapt resource value: 0x7f040051
			public const int show_from_wx_tip = 2130968657;
			
			// aapt resource value: 0x7f04002f
			public const int show_from_wx_title = 2130968623;
			
			// aapt resource value: 0x7f040050
			public const int unregister_from_weixin = 2130968656;
			
			// aapt resource value: 0x7f040014
			public const int verify_password_null_tip = 2130968596;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int progress_dialog = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
